version: '3.8'

services:
  api_bot_server:
    container_name: api_bot_server
    build: .
    ports:
      - "3541:3541"
    volumes:
      - .:/app
      # - "C:/DBGestionBot/BotcndRazones:/mnt/images"  # Montar la carpeta en el contenedor en Windows
      - "/home/Bot_Server/DBGestionBot/BotcndRazones:/mnt/images"  # Montar la carpeta en el contenedor en Linux
      - /var/run/docker.sock:/var/run/docker.sock 
    privileged: true
